### PR TITLE
add replication speed measurement

### PR DESCRIPTION
**Pull request by juliangruber**
cc @joehand

### CODE REVIEW

**Comment by joehand** [comment]
What happens if a stream isn't used directly (e.g. if someone does `archive.download` and passes archive to `hyperdrive-archive-swarm` for replication)?Is there still a way to make this work?

**Comment by juliangruber** [comment]
Hm yeah I thought about that too. This method is the generic implementation and should provide the base for any approach we choose.

Having `swarm({ archive, stats })` _could_ work but couples modules to each other. Overwriting `archive.replicate()` could work as well, if we inherit from `archive` and return a wrapper around `.replicate()`. _Or_, we could just monkey patch it (meh).

@mafintosh what do you think?

**Comment by pfrazee** [comment]
I've been using the technique from the old hyperdrive stats repo, where you listen for the 'upload' and 'download' events on the hypercore -- both of which include a `data` chunk. So you take `data.length` and feed that into a `speedometer`. That way you're not tied to the replication pipeline

**Comment by juliangruber** [comment]
@pfrazee cool, like this?

**Comment by pfrazee** [comment]
@juliangruber yep!

**Comment by juliangruber** [comment]
2.2.0

**Pull request merged**
